# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutoBuddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AutoBuddy
   pod 'Firebase/Auth'
   pod 'Firebase/Core'
   pod 'Firebase/Database'
   
   target 'AutoBuddyTests' do
       inherit! :search_paths
       pod 'Firebase'
   end

end
